### ISSUE TITLE
node启动访问问题

### ISSUE THREAD

**Issue by xlgosin** [wuyanwen/thinkjsplus#2]
我想请问下，使用localhost访问返回302，数据库数据也加载不了。
然后只能使用127.0.0.1访问就是正常的。我想是什么原因？
谢谢！

**Comment by wuyanwen** [comment]
本地调试,最好统一,不统一,有时不同的小版本,会认为存在跨域,线上不会存在这样的问题.不必太纠结

**Comment by wuyanwen** [comment]
本地调试,最好统一,不统一,有时不同的小版本,会认为存在跨域,线上不会存在这样的问题.不必太纠结

**Comment by xlgosin** [comment]
部署了这个域名 http://api.4shm.com
可以帮我看下么？账号密码admin/admin 进去就加载不了数据。

**Comment by wuyanwen** [comment]
加前端实战交流群说吧:541024234
