### ISSUE TITLE
你好！项目按教程安装好后内容列表和添加都不管用，也不报错！求解决！！

### ISSUE THREAD

**Issue by zhaomo** [wuyanwen/thinkjsplus#5]
我按照教程安装好了应用，能够正常admin账号登陆，但是里面不管是纪实类型的列表显示和添加还是记事内容的列表显示和添加都是空的，添加新内容完全无用但是也不抱任何错误！我看数据库里也有之前默认的数据！列表也不显示！求问有可能是什么问题啊？

**Comment by wuyanwen** [comment]
看控制台请求吧，很有可能是你没有修改端口造成的。
